config/routes.rb
Rails.application.routes.draw do

  resources :competences


  get 'hello/greeting'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competence.rb
class Competence < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/competences_controller.rb
class CompetencesController < ApplicationController
  before_action :set_competence, only: [:show, :edit, :update, :destroy]

  # GET /competences
  def index
    @competences = Competence.all
  end

  # GET /competences/1
  def show
  end

  # GET /competences/new
  def new
    @competence = Competence.new
  end

  # GET /competences/1/edit
  def edit
  end

  # POST /competences
  def create
    @competence = Competence.new(competence_params)

    respond_to do |format|
      if @competence.save
        format.html { redirect_to @competence, notice: 'Competence was successfully created.' }
        format.json { render :show, status: :created, location: @competence }
      else
        format.html { render :new }
        format.json { render json: @competence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competences/1
  def update
    respond_to do |format|
      if @competence.update(competence_params)
        format.html { redirect_to @competence, notice: 'Competence was successfully updated.' }
        format.json { render :show, status: :ok, location: @competence }
      else
        format.html { render :edit }
        format.json { render json: @competence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competences/1
  def destroy
    @competence.destroy
    respond_to do |format|
      format.html { redirect_to competences_url, notice: 'Competence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competence
      @competence = Competence.find(params[:id])
    end

    def competence_params
      params.require(:competence).permit(:name, :author)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController

  def greeting
    @cities = [[1, 'Уфа']]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competence_helper.rb
module CompetenceHelper
end

app/helpers/competences_helper.rb
module CompetencesHelper
end

app/helpers/hello_controller_helper.rb
module HelloControllerHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/views/competences/_form.html.erb
<%= form_for(competence) do |f| %>
  <% if competence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(competence.errors.count, "error") %> prohibited this competence from being saved:</h2>

      <ul>
      <% competence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competences/edit.html.erb
<h1>Editing Competence</h1>

<%= render 'form', competence: @competence %>

<%= link_to 'Show', @competence %> |
<%= link_to 'Back', competences_path %>

app/views/competences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Competences</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @competences.each do |competence| %>
      <tr>
        <td><%= competence.name %></td>
        <td><%= competence.author %></td>
        <td><%= link_to 'Show', competence %></td>
        <td><%= link_to 'Edit', edit_competence_path(competence) %></td>
        <td><%= link_to 'Destroy', competence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Competence', new_competence_path %>

app/views/competences/new.html.erb
<h1>New Competence</h1>

<%= render 'form', competence: @competence %>

<%= link_to 'Back', competences_path %>

app/views/competences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @competence.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @competence.author %>
</p>

<%= link_to 'Edit', edit_competence_path(@competence) %> |
<%= link_to 'Back', competences_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProfportDraft</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>